/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionCard: typeof import('./src/components/dashboard/ActionCard.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    DashBoard: typeof import('./src/components/DashBoard.vue')['default']
    Header: typeof import('./src/components/dashboard/Header.vue')['default']
    HistoryTable: typeof import('./src/components/dashboard/HistoryTable.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
